#!/usr/bin/env bash
# Download the larger Vosk models and repack them into the .tar.gz format
# vosk-browser needs (alphacephei ships .zip). Output lands in public/models/,
# which Vite copies into the build. The tarballs are git-ignored — they're
# build artifacts, regenerated by this script locally and in CI.
#
# Idempotent: skips a model if its .tar.gz already exists.
#
# Only browser-viable models belong here. vosk-browser runs Vosk in WASM,
# which caps out around 2 GB of memory — so the multi-GB flagship models
# (en-us-0.22, en-in-0.5, gigaspeech, …) are intentionally NOT included;
# they crash the tab. lgraph (~128 MB) and the small models are the ceiling.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODELS_DIR="$SCRIPT_DIR/../public/models"
BASE_URL="https://alphacephei.com/vosk/models"

MODELS=(
  "vosk-model-en-us-0.22-lgraph"
  "vosk-model-small-en-in-0.4"
)

mkdir -p "$MODELS_DIR"

need() { command -v "$1" >/dev/null 2>&1 || { echo "Error: '$1' not found on PATH." >&2; exit 1; }; }
need curl
need unzip
need tar

for name in "${MODELS[@]}"; do
  out="$MODELS_DIR/$name.tar.gz"
  if [[ -f "$out" ]]; then
    echo "✓ $name.tar.gz already present — skipping"
    continue
  fi
  tmp="$(mktemp -d)"
  echo "↓ Downloading $name.zip …"
  curl -fSL "$BASE_URL/$name.zip" -o "$tmp/$name.zip"
  echo "↳ Repacking $name → tar.gz …"
  (cd "$tmp" && unzip -q "$name.zip" && tar czf "$name.tar.gz" "$name")
  mv "$tmp/$name.tar.gz" "$out"
  rm -rf "$tmp"
  echo "✓ $out"
done

echo "Done. Models available in public/models/"
